# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k6nyMYkZ6zZ0hbb99SXMk0mpgF-SEyJR

## Part I: Data Pre-processing
"""

import pandas as pd
# Download the Google Analogy dataset
# !wget http://download.tensorflow.org/data/questions-words.txt


# Preprocess the dataset
file_name = "questions-words"
with open(f"{file_name}.txt", "r") as f:
    data = f.read().splitlines()

# check data from the first 10 entries
for entry in data[:10]:
    print(entry)

# TODO1: Write your code here for processing data to pd.DataFrame
# Please note that the first five mentions of ": " indicate `semantic`,
# and the remaining nine belong to the `syntactic` category.

questions = []
categories = []
sub_categories = []

count = 0

for entry in data:
  if entry[0] == ":":
    # print(entry)
    count += 1
    sub_category = entry

  else:
    questions.append(entry)
    if count < 5:
      categories.append("Semantic")
    else:
      categories.append("Syntactic")
    sub_categories.append(sub_category)

# Create the dataframe
df = pd.DataFrame(
    {
        "Question": questions,
        "Category": categories,
        "SubCategory": sub_categories,
    }
)

df.head()

df.to_csv(f"{file_name}.csv", index=False)


"""## Part II: Use pre-trained word embeddings
- After finish Part I, you can run Part II code blocks only.
"""

import numpy as np
import gensim.downloader
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

data = pd.read_csv("questions-words.csv")

MODEL_NAME = "glove-wiki-gigaword-200"
# You can try other models.
# https://radimrehurek.com/gensim/models/word2vec.html#pretrained-models

# Load the pre-trained model (using GloVe vectors here)
model = gensim.downloader.load(MODEL_NAME)
print("The Gensim model loaded successfully!")


# Do predictions and preserve the gold answers (word_D)
preds = []
golds = []

TP=0
c=0

for analogy in tqdm(data["Question"]):
  # TODO2: Write your code here to use pre-trained word embeddings for getting predictions of the analogy task.
  # You should also preserve the gold answers during iterations for evaluations later.
  """ Hints
  # Unpack the analogy (e.g., "man", "woman", "king", "queen")
  # Perform vector arithmetic: word_b + word_c - word_a should be close to word_d
  # Source: https://github.com/piskvorky/gensim/blob/develop/gensim/models/keyedvectors.py#L776
  # Mikolov et al., 2013: big - biggest and small - smallest
  # Mikolov et al., 2013: X = vector(”biggest”) − vector(”big”) + vector(”small”).
  """
  analogy = analogy.lower().split(' ')
  sims = model.most_similar(positive=[analogy[1], analogy[2]], negative=analogy[0], topn=1)
  preds.append(sims[0][0])
  golds.append(analogy[3])

# Perform evaluations. You do not need to modify this block!!

def calculate_accuracy(gold: np.ndarray, pred: np.ndarray) -> float:
    return np.mean(gold == pred)

golds_np, preds_np = np.array(golds), np.array(preds)
data = pd.read_csv("questions-words.csv")

# Evaluation: categories
for category in data["Category"].unique():
    mask = data["Category"] == category
    golds_cat, preds_cat = golds_np[mask], preds_np[mask]
    acc_cat = calculate_accuracy(golds_cat, preds_cat)
    print(f"Category: {category}, Accuracy: {acc_cat * 100}%")

# Evaluation: sub-categories
for sub_category in data["SubCategory"].unique():
    mask = data["SubCategory"] == sub_category
    golds_subcat, preds_subcat = golds_np[mask], preds_np[mask]
    acc_subcat = calculate_accuracy(golds_subcat, preds_subcat)
    print(f"Sub-Category{sub_category}, Accuracy: {acc_subcat * 100}%")

# Collect words from Google Analogy dataset
SUB_CATEGORY = ": family"

# TODO3: Plot t-SNE for the words in the SUB_CATEGORY `: family`

mask = data["SubCategory"] == SUB_CATEGORY
questions = data["Question"][mask]
queries = set()
for question in questions:
  for q in question.split(' '):
    queries.add(q)
queries = list(queries)
queries_v = [model[q] for q in queries]
queries_v = np.array(queries_v)
tsne = TSNE(n_components=2, random_state=0)
queries_tsne = tsne.fit_transform(queries_v)

x_min, x_max = queries_tsne.min(0), queries_tsne.max(0)
X_norm = (queries_tsne - x_min) / (x_max - x_min)
# X_norm = queries_tsne
plt.figure(figsize=(12, 12))
for i in range(X_norm.shape[0]):
  plt.scatter(X_norm[i, 0], X_norm[i, 1], c='#88c999', s=10)
  plt.text(X_norm[i, 0], X_norm[i, 1], str(queries[i]))

plt.title("Word Relationships from Google Analogy Task")
plt.show()
plt.savefig("word_relationships.png", bbox_inches="tight")


"""### Part III: Train your own word embeddings

### Get the latest English Wikipedia articles and do sampling.
- Usually, we start from Wikipedia dump (https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2). However, the downloading step will take very long. Also, the cleaning step for the Wikipedia corpus ([`gensim.corpora.wikicorpus.WikiCorpus`](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus)) will take much time. Therefore, we provide cleaned files for you.
"""

"""
# Download the split Wikipedia files
# Each file contain 562365 lines (articles).
!gdown --id 1jiu9E1NalT2Y8EIuWNa1xf2Tw1f1XuGd -O wiki_texts_part_0.txt.gz
!gdown --id 1ABblLRd9HXdXvaNv8H9fFq984bhnowoG -O wiki_texts_part_1.txt.gz
!gdown --id 1z2VFNhpPvCejTP5zyejzKj5YjI_Bn42M -O wiki_texts_part_2.txt.gz
!gdown --id 1VKjded9BxADRhIoCzXy_W8uzVOTWIf0g -O wiki_texts_part_3.txt.gz
!gdown --id 16mBeG26m9LzHXdPe8UrijUIc6sHxhknz -O wiki_texts_part_4.txt.gz

# Download the split Wikipedia files
# Each file contain 562365 lines (articles), except the last file.
!gdown --id 17JFvxOH-kc-VmvGkhG7p3iSZSpsWdgJI -O wiki_texts_part_5.txt.gz
!gdown --id 19IvB2vOJRGlrYulnTXlZECR8zT5v550P -O wiki_texts_part_6.txt.gz
!gdown --id 1sjwO8A2SDOKruv6-8NEq7pEIuQ50ygVV -O wiki_texts_part_7.txt.gz
!gdown --id 1s7xKWJmyk98Jbq6Fi1scrHy7fr_ellUX -O wiki_texts_part_8.txt.gz
!gdown --id 17eQXcrvY1cfpKelLbP2BhQKrljnFNykr -O wiki_texts_part_9.txt.gz
!gdown --id 1J5TAN6bNBiSgTIYiPwzmABvGhAF58h62 -O wiki_texts_part_10.txt.gz

# Extract the downloaded wiki_texts_parts files.
!gunzip -k wiki_texts_part_*.gz

# Combine the extracted wiki_texts_parts files.
!cat wiki_texts_part_*.txt > wiki_texts_combined.txt

# Check the first ten lines of the combined file
!head -n 10 wiki_texts_combined.txt
"""

"""Please note that we used the default parameters of [`gensim.corpora.wikicorpus.WikiCorpus`](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus) for cleaning the Wiki raw file. Thus, words with one character were discarded."""

# Now you need to do sampling because the corpus is too big.
# You can further perform analysis with a greater sampling ratio.

import random

wiki_txt_path = "wiki_texts_combined.txt"
# wiki_texts_combined.txt is a text file separated by linebreaks (\n).
# Each row in wiki_texts_combined.txt indicates a Wikipedia article.
random.seed(1111)
sample_size = 0.2
output_path = f"wiki_texts_sampled{sample_size * 100}.txt"

full_size = 5623655 # Full article amount
num_ones = int(full_size * sample_size)
num_zeros = full_size - num_ones
sample_list = [1] * num_ones + [0] * num_zeros
random.shuffle(sample_list)

article_length, sampled_length = 0, 0
with open(wiki_txt_path, "r", encoding="utf-8") as f:
  # TODO4: Sample `20%` Wikipedia articles
  # Write your code here
  with open(output_path, "w", encoding="utf-8") as output_file:
      for index, line in enumerate(f):
        article_length += 1
        if sample_list[index] == 1:
          output_file.write(f"{line}\n")
          sampled_length += 1

# print(article_length, sampled_length)

# TODO5: Train your own word embeddings with the sampled articles
# https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec
# Hint: You should perform some pre-processing before training.
# https://radimrehurek.com/gensim/parsing/preprocessing.html
# https://radimrehurek.com/gensim/corpora/dictionary.html

import nltk
from nltk.stem import WordNetLemmatizer as wnl
from gensim.parsing.preprocessing import remove_stopwords
from gensim.models import Word2Vec


nltk.download('words')
nltk.download('wordnet')

with open(output_path, "r", encoding="utf-8") as f:
  contents = f.readlines()
  words = set(nltk.corpus.words.words())
  with open(f'wiki_texts_sampled{sample_size * 100}_preprocessed.txt', "w", encoding="utf-8") as f:
    for index, line in enumerate(contents): 
      # Remove non-English words
      # https://www.nltk.org/api/nltk.tokenize.regexp.html#nltk.tokenize.regexp.wordpunct_tokenize
      content = " ".join(w for w in nltk.wordpunct_tokenize(line) if w.lower() in words or not w.isalpha())
      # print('non-English', content)
      # Remove stop words
      content = remove_stopwords(content)
      # print('stop word', content)
      # Lemmatization (e.g., rocks -> rock)
      # https://www.nltk.org/api/nltk.stem.wordnet.html#nltk.stem.wordnet.WordNetLemmatizer.lemmatize
      content = " ".join(wnl().morphy(w) for w in content.split(" ") if wnl().morphy(w) != None)
      # print('Lemmatization', content)
      f.write(f"{content}\n")
# with open(output_path, "r", encoding="utf-8") as f:
#   model = Word2Vec(contents, vector_size=100, window=5, min_count=5, workers=4)
#   model.save('/workspace/NLP/w2v.model')
sentences = gensim.models.word2vec.LineSentence(output_path)
model = Word2Vec(sentences, vector_size=100, window=5, min_count=3, workers=4)
model.save(f'/workspace/NLP/w2v_{sample_size*100}.model')



data = pd.read_csv("questions-words.csv")

model = Word2Vec.load(f'/workspace/NLP/w2v_{sample_size*100}.model')


# Do predictions and preserve the gold answers (word_D)
preds = []
golds = []

for analogy in tqdm(data["Question"]):
  # TODO6: Write your code here to use your trained word embeddings for getting predictions of the analogy task.
  # You should also preserve the gold answers during iterations for evaluations later.
  """ Hints
  # Unpack the analogy (e.g., "man", "woman", "king", "queen")
  # Perform vector arithmetic: word_b + word_c - word_a should be close to word_d
  # Source: https://github.com/piskvorky/gensim/blob/develop/gensim/models/keyedvectors.py#L776
  # Mikolov et al., 2013: big - biggest and small - smallest
  # Mikolov et al., 2013: X = vector(”biggest”) − vector(”big”) + vector(”small”).
  """
  analogy = analogy.lower().split(' ')
  sims = model.wv.most_similar(positive=[analogy[1], analogy[2]], negative=analogy[0], topn=1)
  preds.append(sims[0][0])
  golds.append(analogy[3])

golds_np, preds_np = np.array(golds), np.array(preds)


def calculate_accuracy(gold: np.ndarray, pred: np.ndarray) -> float:
    return np.mean(gold == pred)

# Evaluation: categories
for category in data["Category"].unique():
    mask = data["Category"] == category
    golds_cat, preds_cat = golds_np[mask], preds_np[mask]
    acc_cat = calculate_accuracy(golds_cat, preds_cat)
    print(f"Category: {category}, Accuracy: {acc_cat * 100}%")

# Evaluation: sub-categories
for sub_category in data["SubCategory"].unique():
    mask = data["SubCategory"] == sub_category
    golds_subcat, preds_subcat = golds_np[mask], preds_np[mask]
    acc_subcat = calculate_accuracy(golds_subcat, preds_subcat)
    print(f"Sub-Category{sub_category}, Accuracy: {acc_subcat * 100}%")

# Collect words from Google Analogy dataset
SUB_CATEGORY = ": family"

# TODO7: Plot t-SNE for the words in the SUB_CATEGORY `: family`

mask = data["SubCategory"] == SUB_CATEGORY
questions = data["Question"][mask]
queries = set()
for question in questions:
  for q in question.split(' '):
    queries.add(q)
queries = list(queries)
queries_v = [model.wv[q] for q in queries]
queries_v = np.array(queries_v)
tsne = TSNE(n_components=2, random_state=0)
queries_tsne = tsne.fit_transform(queries_v)

# x_min, x_max = queries_tsne.min(0), queries_tsne.max(0)
# X_norm = (queries_tsne - x_min) / (x_max - x_min)
X_norm = queries_tsne

plt.figure(figsize=(12, 12))
for i in range(X_norm.shape[0]):
  plt.text(X_norm[i, 0], X_norm[i, 1], str(queries[i]))
  plt.scatter(X_norm[i, 0], X_norm[i, 1], c='#88c999')


plt.title("Word Relationships from Google Analogy Task")
plt.show()
plt.savefig(f"word_relationships_{sample_size*100}.png", bbox_inches="tight")

print(f'Sample size: {sample_size*100}%')